### ISSUE TITLE
Hover Mode is conflicting with Ladders.

### ISSUE THREAD

**Issue by CrossVas** [CyberdyneCC/SimplyJetpacks-2#103]
Hey!

So the problem is simple:
If you have a jetpack equipped (with enabled Hover Mode) you will not be able to go up on ladder.
Tried also with: 

- Rope Ladder and Jaded Ladder from OB;
- Dark Steel Ladder from EIO.

[Imgur](https://imgur.com/kOg4aDc)

**Comment by thundr** [comment]
This has been an "issue" since 1.7. 

IMO, this is expected and intended behavior. If you have hover mode turned on, that means that you want your movement controlled by the jetpack only. Try to think of it like attempting to climb a ladder while a jetpack is boosting you down trying to keep you in place :)

**Comment by CrossVas** [comment]
So, if I understand correctly, I have to use another way to go up (Elevator or Travel anchor).
Okay.
Thanks.

**Comment by thundr** [comment]
I think the idea is that you use the jetpack to go up... but yes.
