### ISSUE TITLE
No jetpacks

### ISSUE THREAD

**Issue by diefesson** [CyberdyneCC/SimplyJetpacks-2#126]
just creative jetpack is registered, Thermal Expansion integration is TRUE and every jetpack tuning config gui is empty

I am using lastest version

(English isn't my main language)

**Comment by Tomson124** [comment]
Can you provide a list of the mods and the verison for each of them please?

**Comment by UpperManglement** [comment]
I was having a very similar issue for a while, although I don't have Thermal installed, I have EnderIO and Redstone Arsenal instead.  This is my mod list, everything is on the latest available version on Curse - https://pastebin.com/HLfFSqDa - EnderIO is version 1.12.2-5.0.36, and Redstone Arsenal is version 1.12.2-2.6.1.15.  My Simply Jetpacks config is attached here: 
[simplyjetpacks.cfg](https://github.com/Tomson124/SimplyJetpacks-2/files/2508954/simplyjetpacks.txt)

I think the issue is having integration enabled in the server config for a mod that isn't installed.  Like when I had left Redstone Repository integration set to true in the config (I do not have RR installed), all I was able to see in JEI was the creative jetpack, creative fluxpack, the various particle effects, and the leather strap.  But once I tweaked the config to _only_ enable integration for mods I had installed, I was able to see the jetpacks and crafting components related to those mods, at least for EnderIO. Nothing seems to have changed for me by enabling Redstone Arsenal, oddly enough

**Comment by Slyklaw** [comment]
I solved this by installing Thermal Dynamics and updating simplyjetpacks.cfg with:
`B:"ThermalDynamics integration"=true`

**Comment by kreezxil** [comment]
Installing the optional dependency solved this for and then ofcourse setting it's integration to true.

I strongly suggest making the mod detect if the companion mods are present and then enabling support in the config automatically without requiring user intervention **on the first run ofcourse, ie when the config doesn't exist**.

At the very least have the default be vanilla recipes enabled.

**Comment by Tomson124** [comment]
@kreezxil  the mod is searching for all available companion mods on the first start and sets the integration to true if there are some present. If you add the mods later you have to enable the integration for yourself, as checking everytime and changing the config automatically would cause issues with people's configs who want do specifically disable a certain integration.

**Comment by kreezxil** [comment]
Your mod failed, because it didn't do that. I had to manually set things to
true. And even then while the JEI showed the recipes for the leadstone
jetpack, the pack wouldn't craft. I've removed your mod and installed Iron
Jet Packs instead, which did properly detect my mods and enabled all the
applicable jet packs.

Thank you for attempting to revive a great 1.7.10 modpack, hopefully you
can find a solution that works 100% of the time and has the least amount of
issues going forward.

**Comment by finalchild** [comment]
This is affecting me as well.
I'm using Thermal Expansion without Thermal Dynamics.
`B:"ThermalExpansion integration"=true`
Still, only the Creative Jetpack is added to the game.

**Comment by Tomson124** [comment]
@finalchild Can you provide me a list of the mods you have installed and the latest log file?

**Comment by finalchild** [comment]
To verify the condition, I installed minimal set of 8 mods.
CodeChickenLib, CoFH Core, CoFH World, JEI, Redstone Flux, Simply Jetpacks 2, Thermal Expansion, Thermal Foundation. (i.e. Simply Jetpacks 2 + Thermal Expansion + JEI and their dependencies)

I see only 7 items from Simply Jetpacks 2, which are Creative Jetpack, Partical Customizer (Default), Particle Customizer (None), Particle Customizer (Smoke Only), Particle Customizer (Rainbow Smoke), Leather Strap, Creative Flux Pack.

[The config file generated](https://pastebin.com/UwptZfpA)
[latest.log](https://pastebin.com/yr2YS2tV)

I don't see any suspicious lines from Simply Jetpacks in both latest.log and the previous (and initial) log file.

**Comment by finalchild** [comment]
Adding Thermal Dynamics and editing the config file fixed the situation.
Enabling vanilla jetpacks in the config added jetpacks as well.
But I would love to see this bug fixed because my pack does not include Thermal Dynamics.

**Comment by Tomson124** [comment]
I have a few days of work anyway, will have a look at it.

**Comment by Y0ungSandwich** [comment]
Using The latest version of 2.2.12.65 is still doing this no matter the integration configs. 
https://github.com/Y0ungSandwich/Mech-Magic-Rewind/issues/2

**Comment by Tomson124** [comment]
Could you show me your config file please? Did you try just installing SJ2 and its dependencies? To make sure it is not a potential conflict with another mod.

**Comment by Y0ungSandwich** [comment]
Sorry for the late reply haven't had time for dev this week. I did try a clean instance with only SJ2 and Redstone Flux with the same result with fresh default configs. 

https://i.imgur.com/d4T6HMi.png

**Comment by Y0ungSandwich** [comment]
Disregard. I figured it out lol. Thanks!
