### ISSUE TITLE
[1.10.2] NullPointException with Capacitor Packs & Creative Capacitor Banks

### ISSUE THREAD

**Issue by oitsjustjose** [CyberdyneCC/SimplyJetpacks-2#33]
Minecraft Version: 1.10.2

MinecraftForge Version: 12.18.3.2281

SimplyJetpacks Version: 2.1.1.47

__________

**Issue:**

When the player has a capacitor pack equipped and mouses over a Creative Capacitor Bank (from EnderIO), [this crash is produced](https://pastebin.com/HXRMNstq).

This occurs in both my modpack and an isolated testing environment I made for this crash, where only EnderCore, EnderIO (tried with both the latest _stable_ and _alpha_ releases on Curse) were installed alongside SimplyJetpacks.

__________

**Proposed Solution**
Add a nullcheck to [this line of code](https://github.com/CyberdyneCC/SimplyJetpacks-2/blob/master/src/main/java/tonius/simplyjetpacks/item/rewrite/ItemFluxpack.java#L135) - that is, if I understand the crash correctly. My mind's a little numb right now having spent 60 hours coding this last week for work, so yeah....

__________

Once again - let me know if I can do anything!

**Comment by Tomson124** [comment]
Thanks again for the very detailed and helpful issue report :)
I have vocational school next week, there I usually have more freetime than in normal working weeks, I hope I can get some things don in the mod at that time.

**Comment by DylanBruzenak** [comment]
I've also experienced this running resonant rise 4. Different npe, probably built from a branch:

https://pastebin.com/xEfHV5z4

Same repro steps: 100% crash with a creative capacitor from enderio in the toolbar and a jetpack equipped. You can't log in to that character without crashing the server; it isn't just a client crash.

**Comment by Tomson124** [comment]
I already know what is causing it, it is the jetpack trying to charge the capacitor bank but that one can't be charged but is not full either which is why the jetpacks/fluxpacks keep trying to charge it...

**Comment by Ozzymud** [comment]
So was this a problem with all mods that use some form of portable charger? I just got disconnected from a server when I aquired a creative capacitor bank. Waiting on the owner to come back on to fix me. But I did have a draconic capacitor in my inventory set to charge items and armor. Thus my question. Is this something that should be reported to the EdnerIO guys or something that needs to be fixed in all the mods that have a portable charger and cause the crash?  

Here is my side of the log: https://pastebin.com/6zYWHrq3 would have to wait for the server owner to get his side of things. The "java.lang.NullPointerException" bit & capacitor is what got me here from google.
