### ISSUE TITLE
Handheld Thruster/Elytra Integration.

### ISSUE THREAD

**Issue by Pinaz993** [CyberdyneCC/SimplyJetpacks-2#34]
So, I've been playing minecraft with an Elitra, and I'd thought that there'd be a way use elytra-like flight with the jetpack boosting it. (IMO, it's a lot more fun that way.) I think I've come up with a way to accomplish it. 

If you have an item in your hand that puts off thrust, perhaps you could use that to boost like you do with fireworks in 1.11. It would take power, of course, and wouldn't be as powerful as the same tier of jetpack.

Alternatively, you could make it so that the jetpack has elytra integrated into the armor piece. When it's activated via keybind, jet power would boost you in the direction that you're looking, not simply upwards and forwards. Toggling hover mode would immediately retract the elytra.

**Comment by Tomson124** [comment]
Very similar to what was suggested in #4 
I am not a really big fan of the Elytra, but I like the idea combining it with the jetpack. I want to implement upgrades for the jetpacks in the future, but atm I am mostly bug fixing and adding mod compatibility.
As my free time is very limited due to my full time job and apprentice school, I am glad if people donate (PayPal or Patreon) as it gives me the opportunity to invest more time on modding :)
#ShamelessBegging

**Comment by Pinaz993** [comment]
If I could set up the stupid Forge Dev environment, I'd have made a pull request by now.

**Comment by Tomson124** [comment]
Feel free to join our discord, maybe I can help you setting up the dev environment.
https://discord.gg/HhhWRXd
