### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by ghost** [CyberdyneCC/SimplyJetpacks-2#96]
Just updated to the latest version of the mod (2.2.6.43 from 2.2.5.39) and enabled EnderIO compatibility via the config and there are missing textures for all EnderIO based thrusters, armour plating and, dark solarium ingots and reinforced glider wings.

![Missing Textures](https://user-images.githubusercontent.com/30030409/41194141-e8a04c8e-6c0e-11e8-8d32-91b268f09c50.png)

**Comment by thundr** [comment]
So this is actually a funny bug. It turns out GitHub on windows does not look at the capitalization of file names, and so when I fixed the names of all of these textures, Git never actually tracked them as changed files and they never made it into the work I commited. This will be fixed next build, thanks for reporting.

**Comment by thundr** [comment]
For those that encounter this bug, you can get a fixed version from Jenkins until it's updated on Curse http://modmuss50.me:8080/job/SimplyJetpacks-2/job/SimplyJetpacks-2-1.12/44/artifact/build/libs/SimplyJetpacks2-1.12.2-2.2.6.44.jar
